config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

    resource :agent
    resource :contact
    resource :fetch_news

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/agent.rb
class Agent < ActiveRecord::Base
  has_many :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user1.rb
class User1 < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
#  before_filter :authenticate_user!
  def show
    @agents = Agent.all
  end

  def new
    @agent = Agent.new
  end
  def create
    @agent = Agent.new(agent_params)
    if @agent.save
      redirect_to agent_path
    else
      render new_agent_path
    end
  end


  def edit
    @agent = Agent.find(params[:format])
    @contacts = Contact.where(:agent_id => @agent.id)
  end
  def update
    @a = Agent.find(params[:format])
    @a.update_attributes(agent_params)

    redirect_to agent_path
  end

  def destroy
    @agent = Agent.find(params[:format])
    if @agent.destroy
      redirect_to agent_path
    else
      render agent_path
    end
  end

  def agent_params
    params.require(:agent).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    @contact.agent_id = params[:format].to_i
  end
  def create
    @c = Contact.new(contact_params)
    if @c.save
      redirect_to edit_agent_path(@c.agent_id)
    else
      redirect_to edit_agent_path(@c.agent_id)
    end
  end


  def edit
    @contact = Contact.find(params[:format])
  end
  def update
    @c = Contact.find(params[:format])
    @c.update_attributes(contact_params)
    redirect_to edit_agent_path(@c.agent_id)
  end

  def destroy
    @c = Contact.find(params[:format])
    if @c.destroy
      redirect_to edit_agent_path(@c.agent_id)
    else
      redirect_to edit_agent_path(@c.agent_id)
    end
  end



  def contact_params
    params.require(:contact).permit(:addr,:agent_id)
  end
end

app/controllers/fetch_news_controller.rb
require 'date'
require 'rexml/document'
require 'net/http'
include REXML
class FetchNewsController < ApplicationController
  def show
    arr = []
    uri = URI('https://www.discountlandlord.co.uk/news/feed/')
    xml_string = Net::HTTP.get(uri)
    if xml_string != nil
      xmldoc = Document.new(xml_string)
      xmldoc.elements.each("rss/channel/item"){
          |e|
        arr.push(e)
      }
      arr.sort_by{|x| Date.parse(x.elements["pubDate"].text)}.reverse.each{
          |e| puts "Title : " + e.elements["title"].text
        puts "Date : " + e.elements["pubDate"].text
      }
      @arr_news = arr.sort_by{|x| Date.parse(x.elements["pubDate"].text)}.reverse
    end
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/fetch_news_helper.rb
module FetchNewsHelper
end

app/views/agents/edit.html.haml
= form_for @agent, :url => agent_path(@agent), :method => :put do |f|
  = f.label :name, "Agent Name"
  = f.text_field :name
  %br
  = link_to 'new Contact', new_contact_path(@agent)
  %table{:border=>"1"}
    %tr
      %td Contact
      %td Edit
      %td Delete
    - @contacts.each do |contact|
      %tr
        %td= link_to contact.addr, contact_path(contact)
        %td= link_to 'edit', edit_contact_path(contact)
        %td= link_to 'delete', contact_path(contact), :method => :delete
  = f.submit "Done"

app/views/agents/new.html.erb
<%= form_for @agent, :url => agent_path(@agent), :method => :post do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
    <%= f.submit "Create" %>
<% end %>

app/views/agents/show.html.haml
//= link_to 'agent_path', agent_path
//= link_to 'new_agent_path', new_agent_path
//= link_to 'edit_agent_path', edit_agent_path
//= link_to current_user.email,  edit_agent_path

= link_to 'new agent', new_agent_path
%table{:border=>"1"}
  %tr
    %td Agent Name
    %td Edit
    %td Delete
  - @agents.each do |agent|
    %tr
      %td= link_to agent.name, agent_path(agent)
      %td= link_to 'edit', edit_agent_path(agent)
      %td= link_to 'delete', agent_path(agent), :method => :delete

app/views/contacts/edit.html.haml
= form_for @contact, :url => contact_path(@contact), :method => :put do |f|
  = f.label :addr, "Contact"
  = f.text_field :addr
  = f.submit "Update"

app/views/contacts/new.html.haml
///<%= form_for @contact, :url => contact_path(@contact), :method => :post do |f| %>
//    <%= f.label :addr, "Contact" %>
//    <%= f.text_field :addr %>
//    <%= f.label :agent_id, "agent_id" %>
//    <%= f.text_field :agent_id %>
//    <%= f.submit "Create" %>
//<% end %>

= form_for @contact, :url => contact_path(@contact), :method => :post do |f|
  = f.label :addr, "Contact"
  = f.text_field :addr
  = f.label :agent_id, "agent_id"
  = f.text_field :agent_id

  = f.submit "Create"

app/views/fetch_news/show.html.haml
%table{:border=>"1"}
  - @arr_news.each do |f|
    %tr
      %td= f.elements["pubDate"].text
      %td= f.elements["title"].text

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>